[package]
name        = "interop-arrow"
description = "Low level Flix wrappers over Apache Arrow classes and interfaces"
version     = "0.1.0"
flix        = "0.38.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/interop-base"              = "0.6.0"


[mvn-dependencies]
"org.apache.arrow:arrow-format" = "12.0.1"
"org.apache.arrow:arrow-memory-core" = "12.0.1"
"org.apache.arrow:arrow-memory-netty" = "12.0.1"
"org.apache.arrow:arrow-vector" = "12.0.1"
"com.google.flatbuffers:flatbuffers-java" = "2.0.3"
"io.netty:netty-buffer" = "4.1.93.Final"
"io.netty:netty-common" = "4.1.93.Final"
"org.slf4j:slf4j-api" = "2.0.7"
"org.slf4j:slf4j-simple" = "2.0.7"


